sync_pyramid_scheme_users:
  cron: "0 0 * * *"
  class: "SyncPyramidSchemeUsersJob"
generate_statistics:
  cron: "0 * * * *"
  class: "GenerateStatisticsJob"
refresh_hackatime_cache:
  cron: "0 * * * *"
  class: "RefreshHackatimeCacheJob"
